ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule.context-keys-type]
[rule.time-equal]
[rule.time-naming]
[rule.var-declaration]
[rule.unexported-return]
[rule.errorf]
[rule.blank-imports]
[rule.context-as-argument]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
	arguments = [["ID"]]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.indent-error-flow]
[rule.argument-limit]
	arguments = [7]
[rule.cyclomatic]
	arguments = [3]
[rule.empty-block]
[rule.superfluous-else]
[rule.confusing-naming]
[rule.get-return]
[rule.confusing-results]
[rule.deep-exit]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.add-constant]
	arguments = [{maxLitCount = "3", allowInts="0,1,-1"}]
[rule.flag-parameter]
[rule.unnecessary-stmt]
[rule.struct-tag]
[rule.modifies-value-receiver]
[rule.constant-logical-expr]
[rule.bool-literal-in-expr]
[rule.redefines-builtin-id]
[rule.function-result-limit]
	arguments = [3]
[rule.range-val-in-closure]
[rule.range-val-address]
[rule.waitgroup-by-value]
[rule.atomic]
[rule.empty-lines]
[rule.line-length-limit]
	arguments = [100]
[rule.call-to-gc]
[rule.duplicated-imports]
[rule.import-shadowing]
[rule.bare-return]
[rule.unused-receiver]
[rule.unhandled-error]
	arguments = ["fmt.Printf", "fmt.Println"]
[rule.cognitive-complexity]
	arguments = [3]
[rule.string-of-int]
[rule.early-return]
[rule.unconditional-recursion]
[rule.identical-branches]
[rule.defer]
	arguments = [["call-chain", "loop", "method-call", "recover", "return"]]
[rule.useless-break]
[rule.optimize-operands-order]
[rule.use-any]
[rule.datarace]
[rule.comment-spacings]
