name: test-development
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: setup please
        run: curl https://get.please.build | bash
      - name: build
        run: source ~/.profile && plz build ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: setup please
        run: curl https://get.please.build | bash
      - name: test
        run: source ~/.profile && plz test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: setup revive
        run: go install github.com/mgechev/revive@latest
      - name: lint
        run: |
          revive -exclude "plz-out/..." -config ./config.toml -formatter default ./... &2>1 revive_report.txt \
          G_PROBLEMS=$( egrep -v "$(date +%Y/%m/%d)" $REVIVE_REPORT_FILE | wc -l ) \
          if [[ "$G_PROBLEMS" -gt 0 ]]; then \
            echo -e "\033[0;31mError. Number of problems ($G_PROBLEMS) exceeded acceptable value of 0" \
            exit 1 \
          fi
