name: test-development
on:
  push:
    paths:
      - server/**
      - .github/workflows/**
      - third_party/go/**
      - go.mod
      - go.sum
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - name: build
        run: go build -o protols ./server/ctl
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - name: test
        run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - name: setup revive
        run: go install github.com/mgechev/revive@latest
      - name: lint
        run: |
          revive -config ./config.toml -formatter default ./... &2>1 revive_report.txt
          G_PROBLEMS=$( wc -l < revive_report.txt )
          if [[ "$G_PROBLEMS" -gt 0 ]]; then
            echo -e "\033[0;31mError. Number of problems ($G_PROBLEMS) exceeded acceptable value of 0"
            exit 1
          fi
