name: test-development
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: setup please
        run: curl https://get.please.build | bash
      - name: build
        run: plz build ./...
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: setup please
        run: curl https://get.please.build | bash
      - name: test
        run: plz test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: setup revive
        run: go install github.com/mgechev/revive@latest
      - name: lint
        run: revive -exclude "plz-out/..."  -config ./config.toml -formatter default ./...
